import type { CatalogItem, GoalId } from "./types";

export const CATALOG: CatalogItem[] = [
  {
    id: "lions-mane",
    name: "Lion's Mane",
    aliases: ["hericium", "yamabushitake"],
    category: "nootropic",
    summary: "Culinary mushroom used for focus, memory, and nerve growth support.",
    typicalDose: "500–1,000 mg extract, 1–2× daily",
    defaultAmount: 1000,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "Take with food to reduce the chance of stomach upset.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 28 },
      note: "Subtle shifts can show in the first week. Most people judge cognition around weeks 2–4, with a fuller read by 8–12 weeks.",
    },
    increaseAfterDays: 14,
    increaseGuidance:
      "Stay at your starting dose for two weeks. If it sits well, you can step from 500 mg toward 1,000–2,000 mg extract daily, split with meals. Give each step 10–14 days.",
    typicalCeiling: "About 2,000 mg extract / day for most people",
    synergies: ["omega-3", "l-theanine", "bacopa", "vitamin-d"],
    avoidWith: [],
    caution:
      "Stop and speak to a clinician if you notice itch, rash, or breathing changes — mushroom extracts can trigger allergies.",
  },
  {
    id: "l-theanine",
    name: "L-Theanine",
    aliases: ["theanine", "suntheanine"],
    category: "amino",
    summary: "Tea amino acid for calm focus without drowsiness at moderate doses.",
    typicalDose: "100–200 mg, 1–2× daily",
    defaultAmount: 200,
    unit: "mg",
    foodTiming: "any",
    foodWhy:
      "Food does not matter much. Pair with caffeine in the morning, or take it alone in the evening for ease.",
    preferredSlots: ["breakfast", "afternoon"],
    onset: {
      kind: "acute",
      minutes: { min: 30, max: 60 },
      days: { min: 1, max: 7 },
      note: "You should feel a smoother edge within 30–60 minutes. Daily use can settle further over a week. This is not a 30-day compound.",
    },
    increaseAfterDays: 7,
    increaseGuidance:
      "If 100 mg feels like nothing after a few days, try 200 mg. Many people land at 200 mg once or twice a day. Do not rush past 400 mg total without a reason.",
    typicalCeiling: "400 mg / day for most people",
    synergies: ["magnesium", "glycine", "lions-mane"],
    avoidWith: [],
    caution:
      "Can stack with other calming agents. If you feel too flat or sleepy, drop the afternoon dose first.",
  },
  {
    id: "magnesium",
    name: "Magnesium glycinate",
    aliases: ["mag", "magnesium", "glycinate", "bisglycinate"],
    category: "mineral",
    summary: "Well-tolerated magnesium for sleep, muscle ease, and nervous system tone.",
    typicalDose: "200–400 mg elemental, evening",
    defaultAmount: 200,
    unit: "mg",
    foodTiming: "any",
    foodWhy:
      "Glycinate is gentle enough without food. If it upsets your stomach, take it with your last meal instead.",
    preferredSlots: ["bed"],
    onset: {
      kind: "cumulative",
      days: { min: 7, max: 21 },
      note: "Sleep and muscle ease often shift within 1–2 weeks. Full repletion can take a month if you were low.",
    },
    increaseAfterDays: 10,
    increaseGuidance:
      "If 200 mg is fine after 10 days, you can step toward 300–400 mg elemental at night. Back off if stools loosen.",
    typicalCeiling: "350–400 mg elemental / day from supplements unless directed otherwise",
    synergies: ["glycine", "vitamin-d", "l-theanine", "zinc"],
    avoidWith: ["zinc"],
    caution:
      "Separate from high-dose zinc by a few hours. Oxide is harsher on the gut than glycinate.",
  },
  {
    id: "vitamin-d",
    name: "Vitamin D3",
    aliases: ["d3", "cholecalciferol", "vitamin d"],
    category: "vitamin",
    summary: "Fat-soluble vitamin for bone, immune, and mood support — best with a fatty meal.",
    typicalDose: "1,000–4,000 IU morning",
    defaultAmount: 2000,
    unit: "IU",
    foodTiming: "with",
    foodWhy:
      "Needs dietary fat. Breakfast with eggs, yogurt, or oil works. Empty-stomach D3 is poorly absorbed.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 28, max: 56 },
      note: "Blood levels move over 4–8 weeks. Do not judge D3 on how you feel this week.",
    },
    increaseAfterDays: 28,
    increaseGuidance:
      "Do not keep stacking IU without a 25-OH vitamin D blood test. Many adults do well at 1,000–2,000 IU; 4,000 IU is a common ceiling without labs.",
    typicalCeiling: "4,000 IU / day without medical guidance",
    synergies: ["vitamin-k2", "omega-3", "magnesium"],
    avoidWith: [],
    caution: "Fat-soluble — more is not better. Get labs if you supplement through winter.",
  },
  {
    id: "vitamin-k2",
    name: "Vitamin K2 (MK-7)",
    aliases: ["k2", "mk-7", "menaquinone"],
    category: "vitamin",
    summary: "Often paired with D3 to direct calcium into bone rather than soft tissue.",
    typicalDose: "90–200 mcg with D3",
    defaultAmount: 100,
    unit: "mcg",
    foodTiming: "with",
    foodWhy: "Fat-soluble. Take with D3 and breakfast fat.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 28, max: 90 },
      note: "This is a long-game nutrient, not a feel-it-today supplement.",
    },
    increaseAfterDays: 30,
    increaseGuidance: "Most people stay at 90–200 mcg. No need to chase higher doses.",
    typicalCeiling: "200 mcg / day for typical MK-7",
    synergies: ["vitamin-d", "omega-3"],
    avoidWith: [],
    caution: "If you take warfarin or other anticoagulants, talk to your clinician before K2.",
  },
  {
    id: "omega-3",
    name: "Omega-3 (EPA/DHA)",
    aliases: ["fish oil", "epa", "dha", "krill", "algae oil"],
    category: "omega",
    summary: "Marine fats for mood, inflammation, and brain cell membranes.",
    typicalDose: "1–2 g combined EPA+DHA with food",
    defaultAmount: 1000,
    unit: "mg",
    foodTiming: "with",
    foodWhy:
      "With a meal that has fat — breakfast or dinner. Empty stomach often means reflux and fishy burps.",
    preferredSlots: ["breakfast", "dinner"],
    onset: {
      kind: "cumulative",
      days: { min: 21, max: 56 },
      note: "Joint ease and mood often take 3–8 weeks. Cell membranes do not turn over overnight.",
    },
    increaseAfterDays: 21,
    increaseGuidance:
      "If 1 g EPA+DHA is tolerated, some people use 2 g. Check the label for EPA+DHA, not just 'fish oil'.",
    typicalCeiling: "2–3 g EPA+DHA / day unless a clinician sets a protocol",
    synergies: ["vitamin-d", "lions-mane", "curcumin"],
    avoidWith: [],
    caution: "High doses can thin blood. Pause before surgery and tell your clinician.",
  },
  {
    id: "ashwagandha",
    name: "Ashwagandha",
    aliases: ["ksm-66", "sensoril", "withania"],
    category: "adaptogen",
    summary: "Adaptogen used for stress load, recovery, and evening wind-down.",
    typicalDose: "300–600 mg standardized extract",
    defaultAmount: 600,
    unit: "mg",
    foodTiming: "with",
    foodWhy:
      "With dinner is typical. Some extracts feel sedating — keep it off mornings if it slows you.",
    preferredSlots: ["dinner", "bed"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Stress and sleep scores usually need 2–6 weeks. Do not expect a benzo-like hit.",
    },
    increaseAfterDays: 14,
    increaseGuidance: "Start 300 mg. If well tolerated after two weeks, 600 mg is a common target.",
    typicalCeiling: "600 mg standardized extract / day",
    synergies: ["magnesium", "l-theanine", "rhodiola"],
    avoidWith: [],
    caution:
      "Skip if you are pregnant, have thyroid disease, or take sedatives unless a clinician agrees. Cycle 8 weeks on / 2 off if you use it long term.",
  },
  {
    id: "rhodiola",
    name: "Rhodiola",
    aliases: ["rhodiola rosea", "salidroside"],
    category: "adaptogen",
    summary: "Morning adaptogen for fatigue and mental stamina.",
    typicalDose: "200–400 mg, morning",
    defaultAmount: 200,
    unit: "mg",
    foodTiming: "empty",
    foodWhy: "Works best 15–30 minutes before breakfast. Food blunts the lift for many people.",
    preferredSlots: ["wake"],
    onset: {
      kind: "acute",
      minutes: { min: 40, max: 90 },
      days: { min: 7, max: 21 },
      note: "A lighter, clearer feel can show the first mornings. The stamina effect is judged over 1–3 weeks.",
    },
    increaseAfterDays: 10,
    increaseGuidance:
      "If 200 mg is quiet after 10 days, try 300–400 mg in the morning only. Avoid late doses — it can disturb sleep.",
    typicalCeiling: "400 mg / day, morning",
    synergies: ["l-theanine", "ashwagandha"],
    avoidWith: [],
    caution:
      "Stimulating. Skip late day. Use caution with bipolar spectrum or SSRIs — check with a clinician.",
  },
  {
    id: "bacopa",
    name: "Bacopa monnieri",
    aliases: ["brahmi", "bacognize"],
    category: "nootropic",
    summary: "Slow-build memory herb. Patience is the protocol.",
    typicalDose: "300 mg standardized, with food",
    defaultAmount: 300,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "Fat-containing meal. Bacopa is famous for nausea on an empty stomach.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 28, max: 56 },
      note: "Memory trials cluster around 8–12 weeks. If you stop at day 10, you never gave it a chance.",
    },
    increaseAfterDays: 21,
    increaseGuidance:
      "Stay at 300 mg for three weeks before considering a second dose with dinner.",
    typicalCeiling: "300–600 mg standardized / day",
    synergies: ["lions-mane", "omega-3"],
    avoidWith: [],
    caution: "Can cause GI upset and vivid dreams. Not a same-week nootropic.",
  },
  {
    id: "creatine",
    name: "Creatine monohydrate",
    aliases: ["creatine"],
    category: "amino",
    summary: "Best-studied performance powder; also used for cognition under sleep debt.",
    typicalDose: "5 g daily, any time",
    defaultAmount: 5,
    unit: "g",
    foodTiming: "any",
    foodWhy: "Mix with water or food. Timing is not precious — consistency is.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 7, max: 28 },
      note: "Muscle saturation takes 1–4 weeks at 5 g. No loading phase required.",
    },
    increaseAfterDays: 14,
    increaseGuidance: "5 g is the settled dose. Loading 20 g is optional and not required.",
    typicalCeiling: "5–10 g / day",
    synergies: [],
    avoidWith: [],
    caution: "Drink water. If you have kidney disease, this needs a clinician, not an app.",
  },
  {
    id: "zinc",
    name: "Zinc",
    aliases: ["zinc picolinate", "zinc glycinate", "zinc citrate"],
    category: "mineral",
    summary: "Immune and skin mineral. Easy to overdo.",
    typicalDose: "15–30 mg with food",
    defaultAmount: 15,
    unit: "mg",
    foodTiming: "with",
    foodWhy:
      "With food to avoid nausea. Not with coffee, and not at the same moment as high-dose magnesium or iron.",
    preferredSlots: ["dinner"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Skin and immunity shifts take weeks. Acute nausea is a timing problem, not an onset problem.",
    },
    increaseAfterDays: 21,
    increaseGuidance: "Stay near 15–25 mg unless deficient. Long-term high zinc depletes copper.",
    typicalCeiling: "40 mg / day from all sources unless directed",
    synergies: ["vitamin-c"],
    avoidWith: ["iron", "magnesium"],
    caution: "Separate from magnesium and iron by 2+ hours. Do not megadose.",
  },
  {
    id: "vitamin-c",
    name: "Vitamin C",
    aliases: ["ascorbic", "ascorbate"],
    category: "vitamin",
    summary: "Water-soluble antioxidant. Excess becomes expensive urine.",
    typicalDose: "250–1,000 mg",
    defaultAmount: 500,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Anytime. Split larger amounts to spare the gut.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "acute",
      days: { min: 1, max: 14 },
      note: "Tissue levels rise within days. It will not prevent every cold.",
    },
    increaseAfterDays: 7,
    increaseGuidance:
      "If 500 mg sits well, 1,000 mg is plenty for most. Back off if you get loose stool.",
    typicalCeiling: "2,000 mg / day",
    synergies: ["zinc", "iron"],
    avoidWith: [],
    caution: "High doses can upset the gut and interfere with some lab tests.",
  },
  {
    id: "vitamin-b12",
    name: "Vitamin B12",
    aliases: ["methylcobalamin", "cobalamin", "cyanocobalamin"],
    category: "vitamin",
    summary: "Energy and nerve vitamin, especially if you eat little animal food.",
    typicalDose: "500–1,000 mcg, morning",
    defaultAmount: 1000,
    unit: "mcg",
    foodTiming: "any",
    foodWhy: "Morning, with or without food. Methylcobalamin can feel alerting.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 56 },
      note: "If you were deficient, energy and focus can lift over weeks. If you were not, you may feel nothing — that is useful data.",
    },
    increaseAfterDays: 21,
    increaseGuidance:
      "1,000 mcg oral is already high. More rarely helps unless absorption is the issue.",
    typicalCeiling: "1,000–2,000 mcg oral / day",
    synergies: ["folate"],
    avoidWith: [],
    caution: "Ask a clinician before high-dose B12 if you have Leber's or kidney disease.",
  },
  {
    id: "glycine",
    name: "Glycine",
    aliases: [],
    category: "sleep",
    summary: "Amino acid that can deepen the first stretch of sleep.",
    typicalDose: "3 g, 30–60 min before bed",
    defaultAmount: 3,
    unit: "g",
    foodTiming: "any",
    foodWhy: "Before bed, mixed in water. Food is optional.",
    preferredSlots: ["bed"],
    onset: {
      kind: "acute",
      minutes: { min: 30, max: 60 },
      days: { min: 3, max: 14 },
      note: "Sleep quality can shift the first nights. Give it a week before you decide.",
    },
    increaseAfterDays: 7,
    increaseGuidance:
      "3 g is the usual studied amount. 5 g is sometimes used; more is rarely better.",
    typicalCeiling: "5 g at night",
    synergies: ["magnesium", "l-theanine"],
    avoidWith: [],
    caution: "Mild sweetness. Rare GI upset at higher grams.",
  },
  {
    id: "curcumin",
    name: "Curcumin",
    aliases: ["turmeric", "meriva", "bcm-95"],
    category: "other",
    summary: "Turmeric extract for inflammatory tone. Needs fat and often piperine.",
    typicalDose: "500–1,000 mg with a fatty meal",
    defaultAmount: 500,
    unit: "mg",
    foodTiming: "with",
    foodWhy:
      "With fat. Black pepper extract (piperine) or a phytosome form is what makes it absorb.",
    preferredSlots: ["dinner"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Joint comfort is a 2–6 week read, not a next-morning one.",
    },
    increaseAfterDays: 14,
    increaseGuidance: "Stay at 500 mg with food for two weeks, then 1,000 mg if needed.",
    typicalCeiling: "1,000–1,500 mg curcuminoids / day",
    synergies: ["omega-3"],
    avoidWith: [],
    caution:
      "Can interact with blood thinners and some chemotherapies. Not for late pregnancy without advice.",
  },
  {
    id: "coq10",
    name: "CoQ10",
    aliases: ["ubiquinol", "ubiquinone"],
    category: "other",
    summary: "Mitochondrial cofactor, often used with statins or for energy.",
    typicalDose: "100–200 mg with fat, morning",
    defaultAmount: 100,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "Fat-soluble. Breakfast with fat. Ubiquinol is the better-absorbed form for some.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 21, max: 56 },
      note: "Energy changes, if they come, take weeks.",
    },
    increaseAfterDays: 21,
    increaseGuidance:
      "100 mg is a fair start. 200 mg if you are on a statin and a clinician agrees.",
    typicalCeiling: "200–300 mg / day",
    synergies: ["omega-3", "vitamin-d"],
    avoidWith: [],
    caution: "Can interact with warfarin. Morning is better — it can feel alerting.",
  },
  {
    id: "probiotic",
    name: "Probiotic",
    aliases: ["lactobacillus", "bifidobacterium"],
    category: "gut",
    summary: "Live cultures for gut rhythm. Strain and consistency matter more than brand hype.",
    typicalDose: "As labeled, often 10–50 billion CFU",
    defaultAmount: 1,
    unit: "cap",
    foodTiming: "empty",
    foodWhy:
      "Many strains prefer waking, 20+ minutes before food. Follow your bottle if it disagrees.",
    preferredSlots: ["wake"],
    onset: {
      kind: "cumulative",
      days: { min: 7, max: 28 },
      note: "Bloat can move in a week. Broader gut change takes 2–4 weeks. A new strain can worsen things first — give it 10 days unless you are unwell.",
    },
    increaseAfterDays: 14,
    increaseGuidance:
      "Do not stack bottles. One well-chosen product, taken daily, beats rotating five.",
    typicalCeiling: "Follow the label; more CFU is not automatically better",
    synergies: [],
    avoidWith: [],
    caution: "If you are immunocompromised or have a central line, this is a clinician decision.",
  },
  {
    id: "iron",
    name: "Iron",
    aliases: ["ferrous", "bisglycinate", "ferrous sulfate"],
    category: "mineral",
    summary: "Only if you are low. Do not add iron 'just in case'.",
    typicalDose: "Per labs, often 18–65 mg elemental",
    defaultAmount: 25,
    unit: "mg",
    foodTiming: "empty",
    foodWhy:
      "Empty stomach with vitamin C helps absorption. Food, calcium, tea, and coffee block it. If it wrecks your stomach, take with a small meal and accept less absorption.",
    preferredSlots: ["wake"],
    onset: {
      kind: "cumulative",
      days: { min: 28, max: 90 },
      note: "Ferritin moves over months. Energy may lift sooner if you were truly deficient.",
    },
    increaseAfterDays: 30,
    increaseGuidance: "Do not increase without a ferritin check. Iron overload is real.",
    typicalCeiling: "Set by labs, not by this app",
    synergies: ["vitamin-c"],
    avoidWith: ["zinc", "magnesium", "calcium"],
    caution:
      "Keep away from children. Separate from zinc, magnesium, calcium, and thyroid meds by 2+ hours.",
  },
  {
    id: "melatonin",
    name: "Melatonin",
    aliases: [],
    category: "sleep",
    summary: "Sleep-timing hormone. Smaller doses often work better than 10 mg hammers.",
    typicalDose: "0.3–1 mg, 30–60 min before bed",
    defaultAmount: 1,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Before bed, lights low. Food is irrelevant.",
    preferredSlots: ["bed"],
    onset: {
      kind: "acute",
      minutes: { min: 20, max: 45 },
      days: { min: 1, max: 7 },
      note: "This is a tonight compound. If 1 mg does nothing after a week, more milligrams are rarely the answer — timing and light are.",
    },
    increaseAfterDays: 7,
    increaseGuidance: "Try 0.5–1 mg before climbing to 3 mg. 10 mg is seldom a better idea.",
    typicalCeiling: "3 mg for most adults",
    synergies: ["magnesium", "glycine"],
    avoidWith: [],
    caution:
      "Can linger as morning grog. Avoid if you need to be alert overnight. Not for unsupervised long-term use in teens.",
  },
  {
    id: "collagen",
    name: "Collagen peptides",
    aliases: ["hydrolyzed collagen", "gelatin"],
    category: "other",
    summary: "Protein for skin, joints, and a simple morning ritual.",
    typicalDose: "10–20 g in coffee or water",
    defaultAmount: 10,
    unit: "g",
    foodTiming: "any",
    foodWhy: "Anytime. Pair with vitamin C if skin is the goal.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 28, max: 90 },
      note: "Skin and joint reads take 1–3 months.",
    },
    increaseAfterDays: 30,
    increaseGuidance:
      "10 g is a start. 15–20 g is common. More than 20 g is usually just extra protein.",
    typicalCeiling: "20 g / day",
    synergies: ["vitamin-c"],
    avoidWith: [],
    caution: "Allergen if sourced from fish. Not a complete protein on its own.",
  },
  {
    id: "electrolytes",
    name: "Electrolytes",
    aliases: ["lmnt", "sodium", "potassium", "salt"],
    category: "mineral",
    summary: "Sodium, potassium, magnesium for training days, heat, or low-carb eating.",
    typicalDose: "Follow the packet; often 500–1,000 mg sodium",
    defaultAmount: 1,
    unit: "pkt",
    foodTiming: "any",
    foodWhy: "Sip through the morning. Not a replacement for medical dehydration care.",
    preferredSlots: ["breakfast", "afternoon"],
    onset: {
      kind: "acute",
      minutes: { min: 20, max: 40 },
      days: { min: 1, max: 3 },
      note: "Headache and energy from salt/fluid shifts can move the same day.",
    },
    increaseAfterDays: 5,
    increaseGuidance: "Match to sweat and diet. More packets are not a personality.",
    typicalCeiling: "Depends on blood pressure and kidney function",
    synergies: ["magnesium"],
    avoidWith: [],
    caution: "If you have high blood pressure or kidney disease, this needs a clinician.",
  },
  {
    id: "reishi",
    name: "Reishi",
    aliases: ["ganoderma"],
    category: "adaptogen",
    summary: "Evening mushroom for wind-down and immune tone.",
    typicalDose: "1,000 mg extract, evening",
    defaultAmount: 1000,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "With dinner. Can feel heavy if taken in the morning.",
    preferredSlots: ["dinner", "bed"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Sleep smoothness is a 2–4 week read.",
    },
    increaseAfterDays: 14,
    increaseGuidance: "Keep a single evening dose for two weeks before adding more.",
    typicalCeiling: "1,500–2,000 mg extract / day",
    synergies: ["lions-mane", "ashwagandha"],
    avoidWith: [],
    caution: "Mushroom allergy risk. Can theoretically affect platelets at high dose.",
  },
  {
    id: "cordyceps",
    name: "Cordyceps",
    aliases: [],
    category: "adaptogen",
    summary: "Morning mushroom used for training stamina.",
    typicalDose: "1,000 mg extract, morning",
    defaultAmount: 1000,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "With breakfast. Keep it off evenings if it feels stimulating.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 10, max: 28 },
      note: "Training feel is usually judged over 2–4 weeks.",
    },
    increaseAfterDays: 14,
    increaseGuidance: "1,000 mg for two weeks, then 2,000 mg if you still want more.",
    typicalCeiling: "2,000 mg extract / day",
    synergies: ["creatine", "rhodiola"],
    avoidWith: [],
    caution: "Autoimmune or blood-thinning situations need a clinician first.",
  },
  {
    id: "alpha-gpc",
    name: "Alpha-GPC",
    aliases: ["choline", "gpc"],
    category: "nootropic",
    summary: "Choline donor used with focus work. Easy to overshoot into a headache.",
    typicalDose: "300 mg, morning",
    defaultAmount: 300,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Morning, with or without food.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "acute",
      minutes: { min: 30, max: 60 },
      days: { min: 7, max: 21 },
      note: "A sharper session can show the first mornings. Headaches mean you went too high.",
    },
    increaseAfterDays: 10,
    increaseGuidance: "Stay at 300 mg. 600 mg is a ceiling for most, not a target.",
    typicalCeiling: "600 mg / day",
    synergies: ["lions-mane", "l-theanine"],
    avoidWith: [],
    caution: "High doses can cause headache, restlessness, or low mood. Less is usually better.",
  },
  {
    id: "berberine",
    name: "Berberine",
    aliases: [],
    category: "other",
    summary: "Plant alkaloid used around meals for glucose. It is a real drug-like compound.",
    typicalDose: "500 mg with a carbohydrate-heavy meal",
    defaultAmount: 500,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "With lunch or dinner, not on an empty stomach.",
    preferredSlots: ["lunch", "dinner"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Glucose metrics need weeks and actual measurements.",
    },
    increaseAfterDays: 14,
    increaseGuidance:
      "500 mg with the biggest carb meal. A second 500 mg with another meal is sometimes used. This is not a casual add.",
    typicalCeiling: "1,000–1,500 mg / day split with meals",
    synergies: [],
    avoidWith: [],
    caution:
      "Interacts with many drugs and can upset the gut. Not for pregnancy. Talk to a clinician if you use glucose-lowering medication.",
  },
  {
    id: "taurine",
    name: "Taurine",
    aliases: ["l-taurine"],
    category: "amino",
    summary: "Amino acid for calm, hydration in muscles, and evening wind-down.",
    typicalDose: "500–2,000 mg daily",
    defaultAmount: 1000,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Food does not matter. Many take it in the evening for its calming feel.",
    preferredSlots: ["dinner"],
    onset: {
      kind: "cumulative",
      days: { min: 7, max: 28 },
      note: "A calmer evening can show in the first week; training and heart benefits are judged over weeks.",
    },
    increaseAfterDays: 14,
    increaseGuidance:
      "Start at 500–1,000 mg. If well tolerated after two weeks, 2,000 mg is a common daily amount.",
    typicalCeiling: "3,000 mg / day for most people",
    synergies: ["magnesium", "glycine"],
    avoidWith: [],
    caution:
      "Generally well tolerated. Check with a clinician if you take blood-pressure medication.",
  },
  {
    id: "saffron",
    name: "Saffron extract",
    aliases: ["affron", "satiereal", "crocus"],
    category: "other",
    summary: "Standardised saffron extract studied for low mood and stress.",
    typicalDose: "28–30 mg extract daily",
    defaultAmount: 28,
    unit: "mg",
    foodTiming: "with",
    foodWhy: "With a meal to keep it gentle on the stomach.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 42 },
      note: "Mood studies usually read results at 4–8 weeks. Do not judge it in the first fortnight.",
    },
    increaseAfterDays: 28,
    increaseGuidance: "Studied doses are around 28–30 mg a day. More is not shown to be better.",
    typicalCeiling: "30 mg extract / day",
    synergies: ["omega-3", "vitamin-d"],
    avoidWith: [],
    caution: "Not for pregnancy. Talk to a clinician if you take antidepressants.",
  },
  {
    id: "apigenin",
    name: "Apigenin",
    aliases: ["chamomile extract"],
    category: "sleep",
    summary: "Chamomile flavonoid used to ease into sleep.",
    typicalDose: "50 mg, 30–60 min before bed",
    defaultAmount: 50,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Before bed; food is not important.",
    preferredSlots: ["bed"],
    onset: {
      kind: "acute",
      minutes: { min: 30, max: 60 },
      days: { min: 1, max: 14 },
      note: "Some feel drowsier the first night; the sleep-quality picture takes a week or two.",
    },
    increaseAfterDays: 7,
    increaseGuidance: "50 mg is the usual amount. Look at timing and wind-down before raising it.",
    typicalCeiling: "50–100 mg / night",
    synergies: ["magnesium", "l-theanine", "glycine"],
    avoidWith: [],
    caution: "Mild sedative effect. Avoid with sedating medication unless your clinician agrees.",
  },
  {
    id: "nac",
    name: "NAC (N-acetyl cysteine)",
    aliases: ["n-acetyl cysteine", "n-acetyl-l-cysteine", "acetylcysteine"],
    category: "amino",
    summary: "Glutathione precursor used for antioxidant and respiratory support.",
    typicalDose: "600 mg, 1–2× daily",
    defaultAmount: 600,
    unit: "mg",
    foodTiming: "any",
    foodWhy: "Absorbs fine either way. Take with food if it upsets your stomach.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 14, max: 56 },
      note: "This is a background compound; most uses are judged over 4–8 weeks, not by feel.",
    },
    increaseAfterDays: 21,
    increaseGuidance:
      "600 mg once a day is a common start; 600 mg twice a day is a common ceiling.",
    typicalCeiling: "1,200–1,800 mg / day",
    synergies: ["glycine", "vitamin-c"],
    avoidWith: [],
    caution:
      "Smells of sulfur — that is normal. Check with a clinician if you have asthma or take nitroglycerin.",
  },
  {
    id: "b-complex",
    name: "B-complex",
    aliases: ["vitamin b complex", "b vitamins", "b-100", "b-50"],
    category: "vitamin",
    summary: "All eight B vitamins for energy metabolism. Bright yellow urine is normal.",
    typicalDose: "1 capsule with breakfast",
    defaultAmount: 1,
    unit: "capsule",
    foodTiming: "with",
    foodWhy: "With your first meal — on an empty stomach it can cause nausea.",
    preferredSlots: ["breakfast"],
    onset: {
      kind: "cumulative",
      days: { min: 7, max: 28 },
      note: "If you were low, energy can lift within a couple of weeks. If not, you may feel nothing.",
    },
    increaseAfterDays: 28,
    increaseGuidance: "There is rarely a reason to take more than one serving a day.",
    typicalCeiling: "1 serving / day",
    synergies: ["magnesium"],
    avoidWith: [],
    caution: "Keep it morning: B vitamins can feel stimulating late in the day.",
  },
];

export const CATALOG_BY_ID = Object.fromEntries(CATALOG.map((item) => [item.id, item])) as Record<
  string,
  CatalogItem
>;

export function searchCatalog(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  return CATALOG.filter((item) => {
    if (item.name.toLowerCase().includes(q)) return true;
    if (item.id.includes(q)) return true;
    if (item.summary.toLowerCase().includes(q)) return true;
    return item.aliases.some((alias) => alias.toLowerCase().includes(q));
  });
}

export function catalogForGoals(goals: GoalId[]) {
  const map: Record<GoalId, string[]> = {
    focus: ["lions-mane", "l-theanine", "bacopa", "omega-3", "alpha-gpc", "creatine"],
    calm: ["l-theanine", "magnesium", "ashwagandha", "reishi", "taurine"],
    sleep: ["magnesium", "glycine", "l-theanine", "ashwagandha", "melatonin", "reishi", "apigenin"],
    energy: ["rhodiola", "vitamin-b12", "vitamin-d", "cordyceps", "creatine", "coq10", "b-complex"],
    mood: ["omega-3", "vitamin-d", "ashwagandha", "lions-mane", "saffron"],
    recovery: ["creatine", "omega-3", "magnesium", "curcumin", "collagen"],
    immunity: ["vitamin-d", "zinc", "vitamin-c", "reishi"],
    longevity: ["omega-3", "vitamin-d", "vitamin-k2", "magnesium", "creatine", "nac"],
  };
  const ids = new Set<string>();
  for (const goal of goals) {
    for (const id of map[goal] ?? []) ids.add(id);
  }
  return CATALOG.filter((item) => ids.has(item.id));
}

export function foodLabel(timing: CatalogItem["foodTiming"] | StackFood) {
  switch (timing) {
    case "empty":
      return "Empty stomach";
    case "with":
      return "With food";
    case "after":
      return "After food";
    default:
      return "Anytime";
  }
}

type StackFood = "empty" | "with" | "after" | "any";
